<?php

namespace Httpd\Commands\Service;

use Mix\Config\IniParser;
use Mix\Console\Command;
use Mix\Console\CommandLine\Flag;
use Mix\Console\PidFileHandler;

/**
 * Class BaseCommand
 * @package Httpd\Commands\Service
 */
class BaseCommand extends Command
{

    /**
     * 提示
     */
    const IS_RUNNING = 'Service is running, PID : %d';
    const NOT_RUNNING = 'Service is not running.';
    const EXEC_SUCCESS = 'Command executed successfully.';

    /**
     * 配置信息
     * @var array
     */
    public $config;

    /**
     * 初始化事件
     */
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 获取配置
        $filename = Flag::string(['c', 'configuration'], '');
        if (empty($configFile)) {
            $filename = 'app.ini';
        }
        $ini = new IniParser([
            'filename' => app()->basePath . DIRECTORY_SEPARATOR . $filename,
        ]);
        $ini->load();
        $this->config = $ini->sections();
    }

    /**
     * 获取pid
     * @return bool|string
     */
    public function getServicePid()
    {
        $handler = new PidFileHandler(['pidFile' => $this->config['"pid_file'] ?? '']);
        return $handler->read();
    }

}
